### ISSUE TITLE
Failed to decrypt

### ISSUE THREAD

**Issue by guinhx** [lambwheit/cocos2dx-xxtea-decryptor#3]
The logic of this XXTea is different to this game, if you can help me decrypt their files I would be grateful.
I have been reverse engineering with IDA, but I believe you have more experience.

Game: https://apkpure.com/br/ddtank-origin/com.road7.ddtankbr.gp/download

Some screenshots of what I've discovered so far:
![image](https://github.com/lambwheit/cocos2dx-xxtea-decryptor/assets/48022890/4f00bce4-ea34-4f8e-b8ca-9799dff47ff4)

![image](https://github.com/lambwheit/cocos2dx-xxtea-decryptor/assets/48022890/33f78b25-c0a6-44b2-957b-57a384999f14)

**Comment by lambwheit** [comment]
ngl but cant you just hook all the xxtea functions and just try to find the key that way?
![image](https://github.com/lambwheit/cocos2dx-xxtea-decryptor/assets/38606611/534a20f0-0c79-4904-b090-5caa8112db55)
what is in that function?

**Comment by lambwheit** [comment]
![image](https://github.com/lambwheit/cocos2dx-xxtea-decryptor/assets/38606611/d9c29ddd-30fc-40be-b252-12f74bf7b3b7)
i dont think you can use this tool to decrypt, the code doesnt look xxtea encrypted, there are quite a few readable strings

**Comment by lambwheit** [comment]
worse comes to worse, you can just dump the lua from luaL_loadbuffer, wont dump all the luas tho, if it's not being used the lua will not be dumped

**Comment by IlluminatiWave** [comment]
My grain of sand:

_Z13xxtea_decryptPhjS_jPj is the name sometimes given to xxtea_decrypt, so the function is not wrong, it just has another name (the algorithm is the same).

If you try to hook "xxtea_decrypt" it will not work, you have to hook it by its real name (in your case "_Z13xxtea_decryptPhjS_jPj").

Many times you will encounter compiled LUA files (luajit), so you will have to find out what version of luajit you are using, to pass the compiled lua to Bytecode.

As mentioned, it has a lot of readable strings, it looks like the shell of a lua file with encryption (specifically return [unintelligible code]).

You will have to analyze what encryption algorithm they are using in Lual_loadbuffer (there should be something for that, because that code as such would not work in LUAC, you have to decrypt those strings, and a function close to lual_loadbuffer should be able to convert it to valid luac)

the regular form is " LJ" (the blank space is not a space, it's a character that can't be seen xD)
